services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: weblab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d weblab"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
